name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: srvr

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        sudo docker build \
          --network host \
          -t registry.srvr.site/ip-info:latest \
          -f Dockerfile .

    - name: Push Docker image
      run: |
        sudo docker push registry.srvr.site/ip-info:latest

    - name: Trigger Portainer Webhook
      run: |
        curl -X POST https://portainer.srvr.site/api/stacks/webhooks/644d1d9d-f626-46ae-88fe-bf29170d9bf0
  
